# Generated by Django 6.0.2 on 2026-02-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('orders', 'Order'), ('review', 'Review'), ('payment', 'Payment'), ('message', 'Message'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('read_status', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
